print("Started")
board = Board(5,5)
ai = AI(3)
board.place(0, 'O')
board.place(ai.get_best_move(board), 'X')
print(board)
board.place(1, 'O')
board.place(ai.get_best_move(board), 'X')
print(board)
board.place(2, 'O')
board.place(ai.get_best_move(board), 'X')
print(board)

print(ai.get_best_move(board))